/fbot_agent:
  fbot_agent_node:
    ros__parameters:
      llm_model: ollama/gemma3:4b
      camera_topic: /multisense_1/aux/image_color
      named_poses:
        dinning_room: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]