/fbot_agent:
  fbot_agent_node:
    ros__parameters:
      llm_model: ollama/gemma3:4b
      camera_topic: /multisense_1/aux/image_color
      named_poses:
        dinning_room: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        kitchen: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        living_room: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        bedroom: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        bed: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        sofa: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        tv_stand: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        desk: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        bedside_table: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        office: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        dishwasher: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        cabinet: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        refrigerator: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        shelf: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        trash_bin: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        waste_basket: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        sink: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
        start_point: [-2.26, 5.69, 0.0, 0.0, 0.0, -0.73, 0.68]
      object_labels:
        - person
        - cup
        - bottle
        - chair
        - monitor
        - apple
        - tv
        - bowl
        - banana